### ISSUE TITLE
Fix relevant characters for links

### ISSUE THREAD

**Issue by oswalpalash** [oswalpalash/start#1]
Some links have different characters assigned to them. This breaks the overall sync of the page.
Fix those characters.

**Comment by Krashcan** [comment]
You mean like, changing the character key for flock under eig,should be made 'f' from 'a' ?

**Comment by oswalpalash** [comment]
Yes @Krashcan

**Comment by Krashcan** [comment]
Okk , I am on it.

**Comment by Krashcan** [comment]
Hey, i am new to open source.I fixed the issue but Its embarassing that I dont know how to proceed after making changes to the repository locally.

**Comment by Jeyveen7** [comment]
@Krashcan Create a pull request and @oswalpalash will take care of the rest.

**Comment by Krashcan** [comment]
thank you @Jeyveen7

**Comment by oswalpalash** [comment]
Closing this issue, 👍
